FROM ubuntu:latest
RUN apt-get update && apt-get install -y apache2 git
RUN rm -rf /var/www/html/*
RUN git clone https://github.com/Mouhamed-dridi/startupWebSite.git /var/www/html/
CMD ["apache2ctl", "-D", "FOREGROUND"]
